/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildingArtTimeline: typeof import('./src/components/BuildingArtTimeline.vue')['default']
    BuildingFloatingNav: typeof import('./src/components/BuildingFloatingNav.vue')['default']
    BuildingQuizComp: typeof import('./src/components/BuildingQuizComp.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTour: typeof import('element-plus/es')['ElTour']
    ElTourStep: typeof import('element-plus/es')['ElTourStep']
    MusicPlayComp: typeof import('./src/components/MusicPlayComp.vue')['default']
    NavbarComp: typeof import('./src/components/NavbarComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TourComp: typeof import('./src/components/TourComp.vue')['default']
  }
}
