import type { BuildingCategory } from './types';
import residenceCover from '@/assets/images/building-covers/residence-cover.png';

export const buildingCatalog: BuildingCategory[] = [
  {
    id: 'residence',
    title: '民居',
    alias: '宅院聚落',
    english: 'Residences',
    seal: '宅',
    summary: '从日常居住空间切入，观察院落、聚落与地域适应性的营造线索。',
    description: '以宅院、聚落与山地住居为主线，适合承接后续真实建筑图册与地方分区数据。',
    accent: '#b45b47',
    outline: '#8d3b32',
    coverVariant: 'residence-courtyard',
    coverImage: residenceCover,
    coverPosition: 'center center',
    coverSize: 'contain',
    useCoverAsPoster: true,
    groups: [
      {
        id: 'residence-mingqing',
        title: '明清时期',
        subtitle: '院落与商宅',
        description: '明清民居更强调礼序、围合与家族聚居，适合呈现板块化图册浏览。',
        previewVariant: 'residence-courtyard',
        items: [
          {
            id: 'residence-yongding',
            name: '永定土楼',
            dynasty: '明',
            year: 1608,
            eraLabel: '明·万历三十六年',
            region: '福建 龙岩',
            summary: '围合式聚落民居，以厚墙与内向院落形成强防御性和家族凝聚感。',
            tags: ['围合', '夯土', '聚族'],
            variant: 'residence-tulou',
          },
          {
            id: 'residence-qiao',
            name: '乔家大院',
            dynasty: '清',
            year: 1756,
            eraLabel: '清·乾隆二十一年',
            region: '山西 晋中',
            summary: '北方合院民居代表，院落层层递进，轴线秩序鲜明。',
            tags: ['合院', '轴线', '晋商'],
            variant: 'residence-courtyard',
          },
          {
            id: 'residence-kaiping',
            name: '开平碉楼',
            dynasty: '清末',
            year: 1900,
            eraLabel: '清末',
            region: '广东 江门',
            summary: '侨乡民居与瞭望防御结合，立面上呈现中西交织的时代特征。',
            tags: ['碉楼', '侨乡', '防御'],
            variant: 'residence-diaolou',
          },
        ],
      },
      {
        id: 'residence-songyuan',
        title: '宋元时期',
        subtitle: '街巷与厅屋',
        description: '以宋元厅屋、街坊宅院和山地住居原型为线索，展示早期生活空间的类型差异。',
        previewVariant: 'residence-stilted',
        items: [
          {
            id: 'residence-song-hall',
            name: '宋式厅屋原型',
            dynasty: '北宋',
            year: 1100,
            eraLabel: '北宋·中期',
            region: '江南 地区',
            summary: '厅堂前置、厢房围合，适合表现早期院宅的平面秩序。',
            tags: ['厅屋', '院落', '江南'],
            variant: 'residence-courtyard',
          },
          {
            id: 'residence-yuan-block',
            name: '元代街坊宅院原型',
            dynasty: '元',
            year: 1290,
            eraLabel: '元·中期',
            region: '华北 地区',
            summary: '沿街商业与后部起居并置，体现坊巷住居的复合性。',
            tags: ['街坊', '宅院', '复合'],
            variant: 'residence-courtyard',
          },
          {
            id: 'residence-stilted-proto',
            name: '山地吊脚楼原型',
            dynasty: '元末明初',
            year: 1380,
            eraLabel: '元末明初',
            region: '西南 山地',
            summary: '依坡架空、廊道串联，凸显木构住居对地形与气候的适应。',
            tags: ['山地', '架空', '廊道'],
            variant: 'residence-stilted',
          },
        ],
      },
      {
        id: 'residence-structure',
        title: '聚落结构',
        subtitle: '院、楼、寨',
        description: '按构成方式切分民居图册，可直接替换成后续真实专题数据。',
        previewVariant: 'residence-tulou',
        items: [
          {
            id: 'residence-siheyuan',
            name: '北方四合院原型',
            dynasty: '明清',
            year: 1650,
            eraLabel: '明清沿用',
            region: '华北 地区',
            summary: '强调中轴正房、左右厢房与前院门屋的完整围合关系。',
            tags: ['四合院', '礼序', '围合'],
            variant: 'residence-courtyard',
          },
          {
            id: 'residence-weilong',
            name: '围龙屋原型',
            dynasty: '清',
            year: 1720,
            eraLabel: '清·中期',
            region: '岭南 客家地区',
            summary: '半环抱式院落与后方山墙结合，形成聚族而居的防御轮廓。',
            tags: ['围龙屋', '客家', '半围合'],
            variant: 'residence-tulou',
          },
          {
            id: 'residence-watchtower-cluster',
            name: '侨乡碉楼群原型',
            dynasty: '清末民初',
            year: 1910,
            eraLabel: '清末民初',
            region: '岭南 水乡',
            summary: '塔楼、居室与田间水网共同构成侨乡聚落的独特景观。',
            tags: ['塔楼', '水乡', '聚落'],
            variant: 'residence-diaolou',
          },
        ],
      },
    ],
  },
  {
    id: 'office',
    title: '官府',
    alias: '署治仪门',
    english: 'Administrations',
    seal: '署',
    summary: '以衙署、仪门和公署厅堂为主，展示礼制秩序与行政空间组织。',
    description: '板块上突出“门、堂、廊、库”的层层推进，适合后续承接制度空间解析。',
    accent: '#a44a3d',
    outline: '#7c3029',
    coverVariant: 'office-yamen',
    groups: [
      {
        id: 'office-songyuan',
        title: '宋元时期',
        subtitle: '厅治与公署',
        description: '宋元官署偏重厅治空间与廊庑组合，可用来区分前后场与办事秩序。',
        previewVariant: 'office-hall',
        items: [
          {
            id: 'office-prefecture-hall',
            name: '州府厅堂原型',
            dynasty: '北宋',
            year: 1080,
            eraLabel: '北宋·中期',
            region: '中原 地区',
            summary: '面阔较阔、台基简洁，突出厅堂处理政务与接见的核心作用。',
            tags: ['厅治', '台基', '公署'],
            variant: 'office-hall',
          },
          {
            id: 'office-yuan-gate',
            name: '元代路府仪门原型',
            dynasty: '元',
            year: 1295,
            eraLabel: '元·中期',
            region: '华北 地区',
            summary: '以门厅作为权力过滤节点，串联前场、正堂与侧向办公空间。',
            tags: ['仪门', '路府', '过滤'],
            variant: 'office-gate',
          },
          {
            id: 'office-corridor-yard',
            name: '库庑连廊组合',
            dynasty: '元',
            year: 1320,
            eraLabel: '元·后期',
            region: '北方 地区',
            summary: '通过廊庑连接大堂、文书与仓储空间，形成完整的政务院落。',
            tags: ['廊庑', '库房', '政务'],
            variant: 'office-yamen',
          },
        ],
      },
      {
        id: 'office-mingqing',
        title: '明清时期',
        subtitle: '衙署体制',
        description: '明清官署体系更稳定，适合用卡片与时间轴串联典型门厅、大堂和府邸空间。',
        previewVariant: 'office-yamen',
        items: [
          {
            id: 'office-pingyao',
            name: '平遥县衙大堂范式',
            dynasty: '明清',
            year: 1389,
            eraLabel: '明清沿用',
            region: '山西 平遥',
            summary: '由仪门、大堂、二堂递进组织政务空间，形制清晰且便于分层演示。',
            tags: ['县衙', '大堂', '中轴'],
            variant: 'office-yamen',
          },
          {
            id: 'office-governor',
            name: '总督署仪门范式',
            dynasty: '清',
            year: 1732,
            eraLabel: '清·雍正年间',
            region: '华北 地区',
            summary: '门、堂、廊连续推进，强调行政威仪与等级分隔。',
            tags: ['总督署', '仪门', '威仪'],
            variant: 'office-gate',
          },
          {
            id: 'office-gongwangfu',
            name: '恭王府银安殿',
            dynasty: '清',
            year: 1777,
            eraLabel: '清·乾隆四十二年',
            region: '北京 西城',
            summary: '府邸等级空间兼具官式构架和宅第礼序，适合作为晚期样本。',
            tags: ['府邸', '官式', '礼序'],
            variant: 'office-hall',
          },
        ],
      },
      {
        id: 'office-structure',
        title: '礼制结构',
        subtitle: '门、堂、廊、库',
        description: '按结构序列切分，可在后续正式版本中替换成具体构件或平面专题。',
        previewVariant: 'office-gate',
        items: [
          {
            id: 'office-tower-gate',
            name: '谯楼门厅组合',
            dynasty: '明',
            year: 1450,
            eraLabel: '明·中期',
            region: '北方 城镇',
            summary: '入口门厅与谯楼形成立面标志，用于强调前场控制力。',
            tags: ['门厅', '谯楼', '前场'],
            variant: 'office-gate',
          },
          {
            id: 'office-two-hall',
            name: '大堂二堂序列',
            dynasty: '清',
            year: 1680,
            eraLabel: '清·前期',
            region: '中原 地区',
            summary: '前堂处理公事，后堂承接内务，轴线上的等级关系更明确。',
            tags: ['大堂', '二堂', '序列'],
            variant: 'office-hall',
          },
          {
            id: 'office-screen-yard',
            name: '照壁前场组合',
            dynasty: '清',
            year: 1760,
            eraLabel: '清·中期',
            region: '华北 地区',
            summary: '照壁、甬道与前场关系紧密，适合表现官署入口的节奏。',
            tags: ['照壁', '甬道', '前场'],
            variant: 'office-yamen',
          },
        ],
      },
    ],
  },
  {
    id: 'palace',
    title: '皇宫',
    alias: '门阙殿庭',
    english: 'Palaces',
    seal: '宫',
    summary: '聚焦宫城与殿庭空间，强调台基、门阙和多重屋顶形成的礼制气象。',
    description: '这一卷更适合做高等级建筑的视觉锚点，适合作为第二部分中最强视觉重心。',
    accent: '#3e6f61',
    outline: '#2a5449',
    coverVariant: 'palace-hall',
    groups: [
      {
        id: 'palace-tangsong',
        title: '唐宋气象',
        subtitle: '高台与殿庭',
        description: '以唐宋时期的高台大殿、宫城门殿和角亭范式勾勒早期皇家空间印象。',
        previewVariant: 'palace-gate',
        items: [
          {
            id: 'palace-daming',
            name: '大明宫含元殿遗址',
            dynasty: '唐',
            year: 663,
            eraLabel: '唐·龙朔三年',
            region: '陕西 西安',
            summary: '高台大殿是唐代宫殿礼制空间的典型意象，适合作为早期锚点。',
            tags: ['高台', '殿庭', '宫城'],
            variant: 'palace-hall',
          },
          {
            id: 'palace-song-gate',
            name: '北宋宫城门殿原型',
            dynasty: '北宋',
            year: 1100,
            eraLabel: '北宋·中期',
            region: '中原 地区',
            summary: '门阙和前场共同组织朝会动线，强调纵深感与等级秩序。',
            tags: ['门阙', '朝会', '前场'],
            variant: 'palace-gate',
          },
          {
            id: 'palace-garden-tower',
            name: '宫苑转角观阁原型',
            dynasty: '北宋',
            year: 1115,
            eraLabel: '北宋·后期',
            region: '宫苑 园囿',
            summary: '轻巧高阁作为转角观景节点，为皇宫卷增加层次与视线变化。',
            tags: ['高阁', '转角', '观景'],
            variant: 'palace-tower',
          },
        ],
      },
      {
        id: 'palace-mingqing',
        title: '明清宫苑',
        subtitle: '殿、门、朝序',
        description: '明清宫苑保留了更清晰的礼制秩序，适合做分块式图册和大图预览。',
        previewVariant: 'palace-hall',
        items: [
          {
            id: 'palace-taihe',
            name: '故宫太和殿',
            dynasty: '明',
            year: 1420,
            eraLabel: '明·永乐十八年',
            region: '北京 东城',
            summary: '高等级重檐大殿，台基、栏板与屋脊共同构成强烈的权力象征。',
            tags: ['重檐', '台基', '中轴'],
            variant: 'palace-hall',
          },
          {
            id: 'palace-wumen',
            name: '故宫午门',
            dynasty: '明',
            year: 1420,
            eraLabel: '明·永乐十八年',
            region: '北京 东城',
            summary: '门楼与城台合成一体，是宫城礼制入口与视觉门户。',
            tags: ['门楼', '城台', '礼制'],
            variant: 'palace-gate',
          },
          {
            id: 'palace-shenyang',
            name: '沈阳故宫大政殿',
            dynasty: '清',
            year: 1625,
            eraLabel: '清·天命十年',
            region: '辽宁 沈阳',
            summary: '东北皇家建筑样本，适合拉开宫苑建筑在地域上的差异表达。',
            tags: ['宫苑', '地域', '高等级'],
            variant: 'palace-hall',
          },
        ],
      },
      {
        id: 'palace-structure',
        title: '门阙角楼',
        subtitle: '守望与转角',
        description: '结构专题更适合你后续接真实图片和局部细节，如角楼、门阙、台基与栏板。',
        previewVariant: 'palace-tower',
        items: [
          {
            id: 'palace-corner-tower',
            name: '故宫角楼',
            dynasty: '明',
            year: 1420,
            eraLabel: '明·永乐十八年',
            region: '北京 东城',
            summary: '多重屋顶与转角基座构成强识别度，是皇宫卷中最适合做局部特写的类型。',
            tags: ['角楼', '转角', '望楼'],
            variant: 'palace-tower',
          },
          {
            id: 'palace-gate-ritual',
            name: '宫城门阙范式',
            dynasty: '明',
            year: 1450,
            eraLabel: '明·中期',
            region: '宫城 中轴',
            summary: '以门阙与甬道框定前场，强化礼制空间的进入感。',
            tags: ['门阙', '甬道', '进入'],
            variant: 'palace-gate',
          },
          {
            id: 'palace-terrace-axis',
            name: '轴线台基组合',
            dynasty: '清',
            year: 1650,
            eraLabel: '清·前期',
            region: '宫苑 中轴',
            summary: '台基、栏板和重檐形成连贯的轴线递进，适合承接后续构件解析。',
            tags: ['台基', '栏板', '轴线'],
            variant: 'palace-hall',
          },
        ],
      },
    ],
  },
  {
    id: 'bridge',
    title: '桥梁',
    alias: '拱梁廊桥',
    english: 'Bridges',
    seal: '桥',
    summary: '从石拱、梁桥到廊桥，呈现跨水结构与风景性空间的结合方式。',
    description: '桥梁卷适合加入水体、桥面和时间轴联动，能自然形成强烈的横向构图。',
    accent: '#b4824f',
    outline: '#8d6438',
    coverVariant: 'bridge-arch',
    groups: [
      {
        id: 'bridge-stone',
        title: '石拱体系',
        subtitle: '单孔与连拱',
        description: '以石拱桥为入口，突出跨径、券拱和桥面节奏的差异。',
        previewVariant: 'bridge-arch',
        items: [
          {
            id: 'bridge-zhaozhou',
            name: '赵州桥',
            dynasty: '隋',
            year: 605,
            eraLabel: '隋·大业年间',
            region: '河北 赵县',
            summary: '单孔敞肩石拱桥的经典代表，适合作为桥梁卷最早的时间节点。',
            tags: ['石拱', '敞肩', '单孔'],
            variant: 'bridge-arch',
          },
          {
            id: 'bridge-baodai',
            name: '宝带桥',
            dynasty: '唐',
            year: 816,
            eraLabel: '唐·元和十一年',
            region: '江苏 苏州',
            summary: '长桥连拱，桥身舒展，适合表现古桥的延展性构图。',
            tags: ['连拱', '长桥', '水网'],
            variant: 'bridge-arch',
          },
          {
            id: 'bridge-lugou',
            name: '卢沟桥',
            dynasty: '金',
            year: 1189,
            eraLabel: '金·大定二十九年',
            region: '北京 丰台',
            summary: '多孔联拱与桥栏构成更强的节奏感，适合作为中段样本。',
            tags: ['联拱', '桥栏', '石作'],
            variant: 'bridge-arch',
          },
        ],
      },
      {
        id: 'bridge-songyuan',
        title: '宋元桥作',
        subtitle: '海桥与梁桥',
        description: '宋元时期桥梁营造更强调长向跨越与桥亭节点，适合做结构比较。',
        previewVariant: 'bridge-beam',
        items: [
          {
            id: 'bridge-luoyang',
            name: '洛阳桥',
            dynasty: '北宋',
            year: 1059,
            eraLabel: '北宋·嘉祐四年',
            region: '福建 泉州',
            summary: '海港环境中的长梁桥样本，桥墩、桥板和潮汐关系鲜明。',
            tags: ['梁桥', '海港', '长跨'],
            variant: 'bridge-beam',
          },
          {
            id: 'bridge-anping',
            name: '安平桥',
            dynasty: '南宋',
            year: 1138,
            eraLabel: '南宋·绍兴八年',
            region: '福建 晋江',
            summary: '长距离石梁桥代表，适合表现连续桥墩和桥面节奏。',
            tags: ['石梁', '长桥', '连续'],
            variant: 'bridge-beam',
          },
          {
            id: 'bridge-guangji',
            name: '广济桥',
            dynasty: '南宋',
            year: 1171,
            eraLabel: '南宋·乾道七年',
            region: '广东 潮州',
            summary: '桥、亭与水面共同构成复合景观，适合做桥梁卷的视觉变化点。',
            tags: ['复合', '桥亭', '潮汕'],
            variant: 'bridge-beam',
          },
        ],
      },
      {
        id: 'bridge-corridor',
        title: '廊桥风雨',
        subtitle: '桥与亭并置',
        description: '廊桥主题适合放大木构的屋面语言，也便于右侧时间轴做地域线索。',
        previewVariant: 'bridge-corridor',
        items: [
          {
            id: 'bridge-rainbow',
            name: '汴水虹桥图式',
            dynasty: '北宋',
            year: 1105,
            eraLabel: '北宋·后期',
            region: '汴水 市井',
            summary: '拱起桥面与市井流线交织，是桥梁与城市生活结合的典型图景。',
            tags: ['虹桥', '市井', '弧桥'],
            variant: 'bridge-corridor',
          },
          {
            id: 'bridge-fengyu',
            name: '风雨桥原型',
            dynasty: '清末',
            year: 1890,
            eraLabel: '清末',
            region: '西南 侗寨',
            summary: '桥屋合一、可行可憩，强调桥面上的停留体验。',
            tags: ['风雨桥', '侗寨', '桥屋'],
            variant: 'bridge-corridor',
          },
          {
            id: 'bridge-chengyang',
            name: '程阳永济桥',
            dynasty: '民国初年',
            year: 1916,
            eraLabel: '民国初年',
            region: '广西 三江',
            summary: '多亭连桥的木构廊桥代表，适合作为桥梁卷收束节点。',
            tags: ['廊桥', '多亭', '木构'],
            variant: 'bridge-corridor',
          },
        ],
      },
    ],
  },
];

export const sectionUiText = {
  eyebrow: 'Chinese Architecture Catalogue',
  title: '中国古建筑图谱',
  subtitle: '第二部分 · 分类图册',
  copy: '以分块首页、分类分册和时间轴图册构成第二部分的浏览框架，可直接替换成你的正式建筑图片和时期数据。',
};
